//
// AbilityEffectChange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AbilityEffectChange: Codable { 


    public var effectEntries: [Effect]?
    public var versionGroup: VersionGroup?

    public init(effectEntries: [Effect]?, versionGroup: VersionGroup?) {
        self.effectEntries = effectEntries
        self.versionGroup = versionGroup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case effectEntries = "effect_entries"
        case versionGroup = "version_group"
    }

}
