//
// AncientTrait.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RealmSwift

public class AncientTrait: RealmSwift.Object, Codable {


    @objc dynamic public var name: String?
    @objc dynamic public var text: String?

    public convenience init(name: String?, text: String?) {
        self.init()
        
        self.name = name
        self.text = text
    }

}
