//
// AncientTrait.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AncientTrait: Codable { 


    public var name: String?
    public var text: String?

    public init(name: String?, text: String?) {
        self.name = name
        self.text = text
    }

}
