//
// Attack.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Attack: Codable { 


    public var cost: [String]?
    public var name: String?
    public var text: String?
    public var damage: String?
    public var convertedEnergyCost: Int?

    public init(cost: [String]?, name: String?, text: String?, damage: String?, convertedEnergyCost: Int?) {
        self.cost = cost
        self.name = name
        self.text = text
        self.damage = damage
        self.convertedEnergyCost = convertedEnergyCost
    }

}
