//
// Attack.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RealmSwift

public class Attack: RealmSwift.Object, Codable {


    public var cost: [String]?
    @objc dynamic public var name: String?
    @objc dynamic public var text: String?
    @objc dynamic public var damage: String?
    @objc dynamic public var convertedEnergyCost = 0

    public convenience init(cost: [String]?, name: String?, text: String?, damage: String?, convertedEnergyCost: Int = 0) {
        self.init()
        
        self.cost = cost
        self.name = name
        self.text = text
        self.damage = damage
        self.convertedEnergyCost = convertedEnergyCost
    }

}
