//
// AwesomeName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AwesomeName: Codable { 


    public var awesomeName: String?
    public var language: Language?

    public init(awesomeName: String?, language: Language?) {
        self.awesomeName = awesomeName
        self.language = language
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case awesomeName = "awesome_name"
        case language
    }

}
