//
// Berry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Berry: Codable { 


    public var id: Int?
    public var name: String?
    public var growthTime: Int?
    public var maxHarvest: Int?
    public var naturalGiftPower: Int?
    public var size: Int?
    public var smoothness: Int?
    public var soilDryness: Int?
    public var firmness: BerryFirmness?
    public var flavors: [BerryFlavorMap]?
    public var item: Item?
    public var naturalGiftType: ModelType?

    public init(id: Int?, name: String?, growthTime: Int?, maxHarvest: Int?, naturalGiftPower: Int?, size: Int?, smoothness: Int?, soilDryness: Int?, firmness: BerryFirmness?, flavors: [BerryFlavorMap]?, item: Item?, naturalGiftType: ModelType?) {
        self.id = id
        self.name = name
        self.growthTime = growthTime
        self.maxHarvest = maxHarvest
        self.naturalGiftPower = naturalGiftPower
        self.size = size
        self.smoothness = smoothness
        self.soilDryness = soilDryness
        self.firmness = firmness
        self.flavors = flavors
        self.item = item
        self.naturalGiftType = naturalGiftType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case growthTime = "growth_time"
        case maxHarvest = "max_harvest"
        case naturalGiftPower = "natural_gift_power"
        case size
        case smoothness
        case soilDryness = "soil_dryness"
        case firmness
        case flavors
        case item
        case naturalGiftType = "natural_gift_type"
    }

}
