//
// BerryFlavorMap.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BerryFlavorMap: Codable { 


    public var potency: Int?
    public var flavor: BerryFlavor?

    public init(potency: Int?, flavor: BerryFlavor?) {
        self.potency = potency
        self.flavor = flavor
    }

}
