//
// CardItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RealmSwift

public class CardItem: RealmSwift.Object, Codable {


    @objc dynamic public var card: Card?

    public convenience init(card: Card?) {
        self.init()
        
        self.card = card
    }

}
