//
// CardItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CardItem: Codable {


    public var card: Card?

    public init(card: Card?) {
        self.card = card
    }

}
