//
// CardsList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public class CardsList: Codable {

    public var cards: [Card]?

    public init(cards: [Card]?) {
        self.cards = cards
    }

}
