//
// ContestType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ContestType: Codable { 


    public var id: Int?
    public var name: String?
    public var names: [ContestName]?

    public init(id: Int?, name: String?, names: [ContestName]?) {
        self.id = id
        self.name = name
        self.names = names
    }

}
