//
// ContestComboSets.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ContestComboSets: Codable { 


    public var normal: ContestComboDetail?
    public var _super: ContestComboDetail?

    public init(normal: ContestComboDetail?, _super: ContestComboDetail?) {
        self.normal = normal
        self._super = _super
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case normal
        case _super = "super"
    }

}
