//
// ContestName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ContestName: Codable { 


    public var color: String?
    public var name: String?
    public var language: Language?

    public init(color: String?, name: String?, language: Language?) {
        self.color = color
        self.name = name
        self.language = language
    }

}
