//
// ContestComboDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ContestComboDetail: Codable { 


    public var useBefore: [Move]?
    public var useAfter: [Move]?

    public init(useBefore: [Move]?, useAfter: [Move]?) {
        self.useBefore = useBefore
        self.useAfter = useAfter
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case useBefore = "use_before"
        case useAfter = "use_after"
    }

}
