//
// ContestEffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ContestEffect: Codable { 


    public var id: Int?
    public var appeal: Int?
    public var jam: Int?
    public var effectEntries: [Effect]?
    public var flavorTextEntries: [FlavorText]?

    public init(id: Int?, appeal: Int?, jam: Int?, effectEntries: [Effect]?, flavorTextEntries: [FlavorText]?) {
        self.id = id
        self.appeal = appeal
        self.jam = jam
        self.effectEntries = effectEntries
        self.flavorTextEntries = flavorTextEntries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case appeal
        case jam
        case effectEntries = "effect_entries"
        case flavorTextEntries = "flavor_text_entries"
    }

}
