//
// Description.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Description: Codable { 


    public var language: Language?
    public var description: String?

    public init(language: Language?, description: String?) {
        self.language = language
        self.description = description
    }

}
