//
// Effect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Effect: Codable { 


    public var effect: String?
    public var language: Language?

    public init(effect: String?, language: Language?) {
        self.effect = effect
        self.language = language
    }

}
