//
// EncounterConditionValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EncounterConditionValue: Codable { 


    public var id: Int?
    public var name: String?
    public var condition: EncounterCondition?
    public var names: [Name]?

    public init(id: Int?, name: String?, condition: EncounterCondition?, names: [Name]?) {
        self.id = id
        self.name = name
        self.condition = condition
        self.names = names
    }

}
