//
// EncounterVersionDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EncounterVersionDetails: Codable { 


    public var rate: Int?
    public var version: Version?

    public init(rate: Int?, version: Version?) {
        self.rate = rate
        self.version = version
    }

}
