//
// EncounterCondition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EncounterCondition: Codable { 


    public var id: Int?
    public var name: String?
    public var names: [Name]?
    public var values: [EncounterConditionValue]?

    public init(id: Int?, name: String?, names: [Name]?, values: [EncounterConditionValue]?) {
        self.id = id
        self.name = name
        self.names = names
        self.values = values
    }

}
