//
// EncounterMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EncounterMethod: Codable { 


    public var id: Int?
    public var name: String?
    public var order: Int?
    public var names: [Name]?

    public init(id: Int?, name: String?, order: Int?, names: [Name]?) {
        self.id = id
        self.name = name
        self.order = order
        self.names = names
    }

}
