//
// FlavorBerryMap.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FlavorBerryMap: Codable { 


    public var potency: Int?
    public var berry: Berry?

    public init(potency: Int?, berry: Berry?) {
        self.potency = potency
        self.berry = berry
    }

}
