//
// FlavorText.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FlavorText: Codable { 


    public var flavorText: String?
    public var language: Language?
    public var version: Version?

    public init(flavorText: String?, language: Language?, version: Version?) {
        self.flavorText = flavorText
        self.language = language
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case flavorText = "flavor_text"
        case language
        case version
    }

}
