//
// GenerationGameIndex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GenerationGameIndex: Codable { 


    public var gameIndex: Int?
    public var generation: Generation?

    public init(gameIndex: Int?, generation: Generation?) {
        self.gameIndex = gameIndex
        self.generation = generation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case gameIndex = "game_index"
        case generation
    }

}
