//
// Generation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Generation: Codable { 


    public var id: Int?
    public var name: String?
    public var abilities: [Ability]?
    public var names: [Name]?
    public var mainRegion: Region?
    public var moves: [Move]?
    public var types: [ModelType]?
    public var versionGroups: [VersionGroup]?

    public init(id: Int?, name: String?, abilities: [Ability]?, names: [Name]?, mainRegion: Region?, moves: [Move]?, types: [ModelType]?, versionGroups: [VersionGroup]?) {
        self.id = id
        self.name = name
        self.abilities = abilities
        self.names = names
        self.mainRegion = mainRegion
        self.moves = moves
        self.types = types
        self.versionGroups = versionGroups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case abilities
        case names
        case mainRegion = "main_region"
        case moves
        case types
        case versionGroups = "version_groups"
    }

}
