//
// Genus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Genus: Codable { 


    public var genus: String?
    public var language: Language?

    public init(genus: String?, language: Language?) {
        self.genus = genus
        self.language = language
    }

}
