//
// GrowthRate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GrowthRate: Codable { 


    public var id: Int?
    public var name: String?
    public var formula: String?
    public var descriptions: [Description]?
    public var levels: [GrowthRateExperienceLevel]?
    public var pokemonSpecies: [PokemonSpecies]?

    public init(id: Int?, name: String?, formula: String?, descriptions: [Description]?, levels: [GrowthRateExperienceLevel]?, pokemonSpecies: [PokemonSpecies]?) {
        self.id = id
        self.name = name
        self.formula = formula
        self.descriptions = descriptions
        self.levels = levels
        self.pokemonSpecies = pokemonSpecies
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case formula
        case descriptions
        case levels
        case pokemonSpecies = "pokemon_species"
    }

}
