//
// GrowthRateExperienceLevel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GrowthRateExperienceLevel: Codable { 


    public var level: Int?
    public var experience: Int?

    public init(level: Int?, experience: Int?) {
        self.level = level
        self.experience = experience
    }

}
