//
// ItemSprites.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ItemSprites: Codable { 


    public var _default: String?

    public init(_default: String?) {
        self._default = _default
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case _default = "default"
    }

}
