//
// ItemPocket.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ItemPocket: Codable { 


    public var id: Int?
    public var name: String?
    public var categories: [ItemCategory]?
    public var names: [Name]?

    public init(id: Int?, name: String?, categories: [ItemCategory]?, names: [Name]?) {
        self.id = id
        self.name = name
        self.categories = categories
        self.names = names
    }

}
