//
// ItemCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ItemCategory: Codable { 


    public var id: Int?
    public var name: String?
    public var items: [Item]?
    public var names: [Name]?
    public var pocket: ItemPocket?

    public init(id: Int?, name: String?, items: [Item]?, names: [Name]?, pocket: ItemPocket?) {
        self.id = id
        self.name = name
        self.items = items
        self.names = names
        self.pocket = pocket
    }

}
