//
// ItemAttribute.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ItemAttribute: Codable { 


    public var id: Int?
    public var name: String?
    public var items: [Item]?
    public var names: [Name]?
    public var descriptions: [Description]?

    public init(id: Int?, name: String?, items: [Item]?, names: [Name]?, descriptions: [Description]?) {
        self.id = id
        self.name = name
        self.items = items
        self.names = names
        self.descriptions = descriptions
    }

}
