//
// ItemHolderPokemonVersionDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ItemHolderPokemonVersionDetail: Codable { 


    public var rarity: Int?
    public var version: Version?

    public init(rarity: Int?, version: Version?) {
        self.rarity = rarity
        self.version = version
    }

}
