//
// Item.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Item: Codable { 


    public var id: Int?
    public var name: String?
    public var cost: Int?
    public var flingPower: Int?
    public var flingEffect: ItemFlingEffect?
    public var attributes: [ItemAttribute]?
    public var category: ItemCategory?
    public var effectEntries: [VerboseEffect]?
    public var flavorTextEntries: [VersionGroupFlavorText]?
    public var gameIndices: [GenerationGameIndex]?
    public var names: [Name]?
    public var sprites: ItemSprites?
    public var heldByPokemon: [ItemHolderPokemon]?
    public var machines: [MachineVersionDetail]?

    public init(id: Int?, name: String?, cost: Int?, flingPower: Int?, flingEffect: ItemFlingEffect?, attributes: [ItemAttribute]?, category: ItemCategory?, effectEntries: [VerboseEffect]?, flavorTextEntries: [VersionGroupFlavorText]?, gameIndices: [GenerationGameIndex]?, names: [Name]?, sprites: ItemSprites?, heldByPokemon: [ItemHolderPokemon]?, machines: [MachineVersionDetail]?) {
        self.id = id
        self.name = name
        self.cost = cost
        self.flingPower = flingPower
        self.flingEffect = flingEffect
        self.attributes = attributes
        self.category = category
        self.effectEntries = effectEntries
        self.flavorTextEntries = flavorTextEntries
        self.gameIndices = gameIndices
        self.names = names
        self.sprites = sprites
        self.heldByPokemon = heldByPokemon
        self.machines = machines
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case cost
        case flingPower = "fling_power"
        case flingEffect = "fling_effect"
        case attributes
        case category
        case effectEntries = "effect_entries"
        case flavorTextEntries = "flavor_text_entries"
        case gameIndices = "game_indices"
        case names
        case sprites
        case heldByPokemon = "held_by_pokemon"
        case machines
    }

}
