//
// ItemFlingEffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ItemFlingEffect: Codable { 


    public var id: Int?
    public var name: String?
    public var effectEntries: [Effect]?
    public var items: [Item]?

    public init(id: Int?, name: String?, effectEntries: [Effect]?, items: [Item]?) {
        self.id = id
        self.name = name
        self.effectEntries = effectEntries
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case effectEntries = "effect_entries"
        case items
    }

}
