//
// Language.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Language: Codable { 


    public var id: Int?
    public var name: String?
    public var official: Bool?
    public var iso639: String?
    public var iso3166: String?
    public var names: [Name]?

    public init(id: Int?, name: String?, official: Bool?, iso639: String?, iso3166: String?, names: [Name]?) {
        self.id = id
        self.name = name
        self.official = official
        self.iso639 = iso639
        self.iso3166 = iso3166
        self.names = names
    }

}
