//
// LocationArea.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LocationArea: Codable { 


    public var id: Int?
    public var name: String?
    public var gameIndex: Int?
    public var encounterMethodRates: [EncounterMethodRate]?
    public var location: Location?
    public var names: [Name]?
    public var pokemonEncounters: [PokemonEncounter]?

    public init(id: Int?, name: String?, gameIndex: Int?, encounterMethodRates: [EncounterMethodRate]?, location: Location?, names: [Name]?, pokemonEncounters: [PokemonEncounter]?) {
        self.id = id
        self.name = name
        self.gameIndex = gameIndex
        self.encounterMethodRates = encounterMethodRates
        self.location = location
        self.names = names
        self.pokemonEncounters = pokemonEncounters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case gameIndex = "game_index"
        case encounterMethodRates = "encounter_method_rates"
        case location
        case names
        case pokemonEncounters = "pokemon_encounters"
    }

}
