//
// Location.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Location: Codable { 


    public var id: Int?
    public var name: String?
    public var region: Region?
    public var names: [Name]?
    public var gameIndices: [GenerationGameIndex]?
    public var areas: [LocationArea]?

    public init(id: Int?, name: String?, region: Region?, names: [Name]?, gameIndices: [GenerationGameIndex]?, areas: [LocationArea]?) {
        self.id = id
        self.name = name
        self.region = region
        self.names = names
        self.gameIndices = gameIndices
        self.areas = areas
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case region
        case names
        case gameIndices = "game_indices"
        case areas
    }

}
