//
// Machine.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Machine: Codable { 


    public var id: Int?
    public var item: Item?
    public var move: Move?
    public var versionGroup: VersionGroup?

    public init(id: Int?, item: Item?, move: Move?, versionGroup: VersionGroup?) {
        self.id = id
        self.item = item
        self.move = move
        self.versionGroup = versionGroup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case item
        case move
        case versionGroup = "version_group"
    }

}
