//
// MachineVersionDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MachineVersionDetail: Codable { 


    public var machine: Machine?
    public var versionGroup: VersionGroup?

    public init(machine: Machine?, versionGroup: VersionGroup?) {
        self.machine = machine
        self.versionGroup = versionGroup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case machine
        case versionGroup = "version_group"
    }

}
