//
// ModelType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ModelType: Codable { 


    public var id: Int?
    public var name: String?
    public var damageRelations: TypeRelations?
    public var gameIndices: [GenerationGameIndex]?
    public var generation: Generation?
    public var moveDamageClass: MoveDamageClass?
    public var names: [Name]?
    public var pokemon: [TypePokemon]?
    public var moves: [Move]?

    public init(id: Int?, name: String?, damageRelations: TypeRelations?, gameIndices: [GenerationGameIndex]?, generation: Generation?, moveDamageClass: MoveDamageClass?, names: [Name]?, pokemon: [TypePokemon]?, moves: [Move]?) {
        self.id = id
        self.name = name
        self.damageRelations = damageRelations
        self.gameIndices = gameIndices
        self.generation = generation
        self.moveDamageClass = moveDamageClass
        self.names = names
        self.pokemon = pokemon
        self.moves = moves
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case damageRelations = "damage_relations"
        case gameIndices = "game_indices"
        case generation
        case moveDamageClass = "move_damage_class"
        case names
        case pokemon
        case moves
    }

}
