//
// MoveStatAffectSets.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MoveStatAffectSets: Codable { 


    public var increase: [MoveStatAffect]?
    public var decrease: [MoveStatAffect]?

    public init(increase: [MoveStatAffect]?, decrease: [MoveStatAffect]?) {
        self.increase = increase
        self.decrease = decrease
    }

}
