//
// MoveStatAffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MoveStatAffect: Codable { 


    public var change: Int?
    public var move: Move?

    public init(change: Int?, move: Move?) {
        self.change = change
        self.move = move
    }

}
