//
// MoveLearnMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MoveLearnMethod: Codable { 


    public var id: Int?
    public var name: String?
    public var descriptions: [Description]?
    public var names: [Name]?
    public var versionGroups: [VersionGroup]?

    public init(id: Int?, name: String?, descriptions: [Description]?, names: [Name]?, versionGroups: [VersionGroup]?) {
        self.id = id
        self.name = name
        self.descriptions = descriptions
        self.names = names
        self.versionGroups = versionGroups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case descriptions
        case names
        case versionGroups = "version_groups"
    }

}
