//
// MoveStatChange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MoveStatChange: Codable { 


    public var change: Int?
    public var stat: Stat?

    public init(change: Int?, stat: Stat?) {
        self.change = change
        self.stat = stat
    }

}
