//
// MoveDamageClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MoveDamageClass: Codable { 


    public var id: Int?
    public var name: String?
    public var descriptions: [Description]?
    public var moves: [Move]?
    public var names: [Name]?

    public init(id: Int?, name: String?, descriptions: [Description]?, moves: [Move]?, names: [Name]?) {
        self.id = id
        self.name = name
        self.descriptions = descriptions
        self.moves = moves
        self.names = names
    }

}
