//
// MoveTarget.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MoveTarget: Codable { 


    public var id: Int?
    public var name: String?
    public var descriptions: [Description]?
    public var names: [Name]?
    public var moves: [Move]?

    public init(id: Int?, name: String?, descriptions: [Description]?, names: [Name]?, moves: [Move]?) {
        self.id = id
        self.name = name
        self.descriptions = descriptions
        self.names = names
        self.moves = moves
    }

}
