//
// MoveAilment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MoveAilment: Codable { 


    public var id: Int?
    public var name: String?
    public var names: [Name]?
    public var moves: [Move]?

    public init(id: Int?, name: String?, names: [Name]?, moves: [Move]?) {
        self.id = id
        self.name = name
        self.names = names
        self.moves = moves
    }

}
