//
// Move.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Move: Codable { 


    public var id: Int?
    public var name: String?
    public var accuracy: Int?
    public var effectChance: Int?
    public var pp: Int?
    public var priority: Int?
    public var power: Int?
    public var contestCombos: ContestComboSets?
    public var contestType: ContestType?
    public var contestEffect: ContestEffect?
    public var damageClass: MoveDamageClass?
    public var effectEntries: [VerboseEffect]?
    public var effectChanges: [AbilityEffectChange]?
    public var flavorTextEntries: [MoveFlavorText]?
    public var generation: Generation?
    public var machines: [MachineVersionDetail]?
    public var meta: MoveMetaData?
    public var names: [Name]?
    public var pastValues: [PastMoveStatValues]?
    public var statChanges: [MoveStatChange]?
    public var superContestEffect: SuperContestEffect?
    public var target: MoveTarget?
    public var type: ModelType?

    public init(id: Int?, name: String?, accuracy: Int?, effectChance: Int?, pp: Int?, priority: Int?, power: Int?, contestCombos: ContestComboSets?, contestType: ContestType?, contestEffect: ContestEffect?, damageClass: MoveDamageClass?, effectEntries: [VerboseEffect]?, effectChanges: [AbilityEffectChange]?, flavorTextEntries: [MoveFlavorText]?, generation: Generation?, machines: [MachineVersionDetail]?, meta: MoveMetaData?, names: [Name]?, pastValues: [PastMoveStatValues]?, statChanges: [MoveStatChange]?, superContestEffect: SuperContestEffect?, target: MoveTarget?, type: ModelType?) {
        self.id = id
        self.name = name
        self.accuracy = accuracy
        self.effectChance = effectChance
        self.pp = pp
        self.priority = priority
        self.power = power
        self.contestCombos = contestCombos
        self.contestType = contestType
        self.contestEffect = contestEffect
        self.damageClass = damageClass
        self.effectEntries = effectEntries
        self.effectChanges = effectChanges
        self.flavorTextEntries = flavorTextEntries
        self.generation = generation
        self.machines = machines
        self.meta = meta
        self.names = names
        self.pastValues = pastValues
        self.statChanges = statChanges
        self.superContestEffect = superContestEffect
        self.target = target
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case accuracy
        case effectChance = "effect_chance"
        case pp
        case priority
        case power
        case contestCombos = "contest_combos"
        case contestType = "contest_type"
        case contestEffect = "contest_effect"
        case damageClass = "damage_class"
        case effectEntries = "effect_entries"
        case effectChanges = "effect_changes"
        case flavorTextEntries = "flavor_text_entries"
        case generation
        case machines
        case meta
        case names
        case pastValues = "past_values"
        case statChanges = "stat_changes"
        case superContestEffect = "super_contest_effect"
        case target
        case type
    }

}
