//
// MoveBattleStylePreference.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MoveBattleStylePreference: Codable { 


    public var lowHpPreference: Int?
    public var highHpPreference: Int?
    public var moveBattleStyle: MoveBattleStyle?

    public init(lowHpPreference: Int?, highHpPreference: Int?, moveBattleStyle: MoveBattleStyle?) {
        self.lowHpPreference = lowHpPreference
        self.highHpPreference = highHpPreference
        self.moveBattleStyle = moveBattleStyle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case lowHpPreference = "low_hp_preference"
        case highHpPreference = "high_hp_preference"
        case moveBattleStyle = "move_battle_style"
    }

}
