//
// Name.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Name: Codable { 


    public var name: String?
    public var language: Language?

    public init(name: String?, language: Language?) {
        self.name = name
        self.language = language
    }

}
