//
// NaturePokeathlonStatAffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct NaturePokeathlonStatAffect: Codable { 


    public var maxChange: Int?
    public var nature: Nature?

    public init(maxChange: Int?, nature: Nature?) {
        self.maxChange = maxChange
        self.nature = nature
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case maxChange = "max_change"
        case nature
    }

}
