//
// NatureStatChange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct NatureStatChange: Codable { 


    public var maxChange: Int?
    public var pokeathlonStat: PokeathlonStat?

    public init(maxChange: Int?, pokeathlonStat: PokeathlonStat?) {
        self.maxChange = maxChange
        self.pokeathlonStat = pokeathlonStat
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case maxChange = "max_change"
        case pokeathlonStat = "pokeathlon_stat"
    }

}
