//
// NaturePokeathlonStatAffectSets.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct NaturePokeathlonStatAffectSets: Codable { 


    public var increase: [NaturePokeathlonStatAffect]?
    public var decrease: [NaturePokeathlonStatAffect]?

    public init(increase: [NaturePokeathlonStatAffect]?, decrease: [NaturePokeathlonStatAffect]?) {
        self.increase = increase
        self.decrease = decrease
    }

}
