//
// PalParkEncounterSpecies.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PalParkEncounterSpecies: Codable { 


    public var baseScore: Int?
    public var rate: Int?
    public var pokemonSpecies: PokemonSpecies?

    public init(baseScore: Int?, rate: Int?, pokemonSpecies: PokemonSpecies?) {
        self.baseScore = baseScore
        self.rate = rate
        self.pokemonSpecies = pokemonSpecies
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case baseScore = "base_score"
        case rate
        case pokemonSpecies = "pokemon_species"
    }

}
