//
// PalParkArea.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PalParkArea: Codable { 


    public var id: Int?
    public var name: String?
    public var names: [Name]?
    public var pokemonEncounters: [PalParkEncounterSpecies]?

    public init(id: Int?, name: String?, names: [Name]?, pokemonEncounters: [PalParkEncounterSpecies]?) {
        self.id = id
        self.name = name
        self.names = names
        self.pokemonEncounters = pokemonEncounters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case names
        case pokemonEncounters = "pokemon_encounters"
    }

}
