//
// PalParkEncounterArea.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PalParkEncounterArea: Codable { 


    public var baseScore: Int?
    public var rate: Int?
    public var area: PalParkArea?

    public init(baseScore: Int?, rate: Int?, area: PalParkArea?) {
        self.baseScore = baseScore
        self.rate = rate
        self.area = area
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case baseScore = "base_score"
        case rate
        case area
    }

}
