//
// Pokedex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Pokedex: Codable { 


    public var id: Int?
    public var name: String?
    public var isMainSeries: Bool?
    public var descriptions: [Description]?
    public var names: [Name]?
    public var pokemonEntries: [PokemonEntry]?
    public var region: Region?
    public var versionGroups: [VersionGroup]?

    public init(id: Int?, name: String?, isMainSeries: Bool?, descriptions: [Description]?, names: [Name]?, pokemonEntries: [PokemonEntry]?, region: Region?, versionGroups: [VersionGroup]?) {
        self.id = id
        self.name = name
        self.isMainSeries = isMainSeries
        self.descriptions = descriptions
        self.names = names
        self.pokemonEntries = pokemonEntries
        self.region = region
        self.versionGroups = versionGroups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case isMainSeries = "is_main_series"
        case descriptions
        case names
        case pokemonEntries = "pokemon_entries"
        case region
        case versionGroups = "version_groups"
    }

}
