//
// PokemonMove.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RealmSwift

public class PokemonMove: RealmSwift.Object, Codable {

    @objc dynamic public var move: Move?

    public convenience init(move: Move?) {
        self.init()
        
        self.move = move
    }

}
