//
// PokemonItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RealmSwift

public class PokemonItem: RealmSwift.Object, Codable {


    @objc dynamic public var name: String?
    @objc dynamic public var url: String?

    public convenience init(name: String?, url: String?) {
        self.init()
        
        self.name = name
        self.url = url
    }
    
    override public class func primaryKey() -> String? {
        return "name"
    }
}
