//
// Pokemon.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Pokemon: Codable { 


    public var abilities: [PokemonAbility]?
    public var baseExperience: Int?
    public var forms: [PokemonForm]?
    public var gameIndices: [VersionGameIndex]?
    public var height: Int?
    public var heldItems: [PokemonHeldItem]?
    public var id: Int?
    public var isDefault: Bool?
    public var locationAreaEncounters: String?
    public var moves: [PokemonMove]?
    public var name: String?
    public var order: Int?
    public var species: PokemonSprites?
    public var sprites: PokemonSpecies?
    public var stats: PokemonStat?
    public var types: PokemonType?
    public var weight: Int?

    public init(abilities: [PokemonAbility]?, baseExperience: Int?, forms: [PokemonForm]?, gameIndices: [VersionGameIndex]?, height: Int?, heldItems: [PokemonHeldItem]?, id: Int?, isDefault: Bool?, locationAreaEncounters: String?, moves: [PokemonMove]?, name: String?, order: Int?, species: PokemonSprites?, sprites: PokemonSpecies?, stats: PokemonStat?, types: PokemonType?, weight: Int?) {
        self.abilities = abilities
        self.baseExperience = baseExperience
        self.forms = forms
        self.gameIndices = gameIndices
        self.height = height
        self.heldItems = heldItems
        self.id = id
        self.isDefault = isDefault
        self.locationAreaEncounters = locationAreaEncounters
        self.moves = moves
        self.name = name
        self.order = order
        self.species = species
        self.sprites = sprites
        self.stats = stats
        self.types = types
        self.weight = weight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case abilities
        case baseExperience = "base_experience"
        case forms
        case gameIndices = "game_indices"
        case height
        case heldItems = "held_items"
        case id
        case isDefault = "is_default"
        case locationAreaEncounters = "location_area_encounters"
        case moves
        case name
        case order
        case species
        case sprites
        case stats
        case types
        case weight
    }

}
