//
// PokemonSprites.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonSprites: Codable { 


    public var frontDefault: String?
    public var frontShiny: String?
    public var frontFemale: String?
    public var frontShinyFemale: String?
    public var backDefault: String?
    public var backShiny: String?
    public var backFemale: String?
    public var backShinyFemale: String?

    public init(frontDefault: String?, frontShiny: String?, frontFemale: String?, frontShinyFemale: String?, backDefault: String?, backShiny: String?, backFemale: String?, backShinyFemale: String?) {
        self.frontDefault = frontDefault
        self.frontShiny = frontShiny
        self.frontFemale = frontFemale
        self.frontShinyFemale = frontShinyFemale
        self.backDefault = backDefault
        self.backShiny = backShiny
        self.backFemale = backFemale
        self.backShinyFemale = backShinyFemale
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case frontDefault = "front_default"
        case frontShiny = "front_shiny"
        case frontFemale = "front_female"
        case frontShinyFemale = "front_shiny_female"
        case backDefault = "back_default"
        case backShiny = "back_shiny"
        case backFemale = "back_female"
        case backShinyFemale = "back_shiny_female"
    }

}
