//
// PokemonSprites.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RealmSwift

public class PokemonSprites: RealmSwift.Object, Codable {

    @objc dynamic public var name: String?
    @objc dynamic public var frontDefault: String?
    @objc dynamic public var frontShiny: String?
    @objc dynamic public var frontFemale: String?
    @objc dynamic public var frontShinyFemale: String?
    @objc dynamic public var backDefault: String?
    @objc dynamic public var backShiny: String?
    @objc dynamic public var backFemale: String?
    @objc dynamic public var backShinyFemale: String?

    public convenience init(name: String?, frontDefault: String?, frontShiny: String?, frontFemale: String?, frontShinyFemale: String?, backDefault: String?, backShiny: String?, backFemale: String?, backShinyFemale: String?) {
        self.init()
        
        self.name = name
        self.frontDefault = frontDefault
        self.frontShiny = frontShiny
        self.frontFemale = frontFemale
        self.frontShinyFemale = frontShinyFemale
        self.backDefault = backDefault
        self.backShiny = backShiny
        self.backFemale = backFemale
        self.backShinyFemale = backShinyFemale
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case frontDefault = "front_default"
        case frontShiny = "front_shiny"
        case frontFemale = "front_female"
        case frontShinyFemale = "front_shiny_female"
        case backDefault = "back_default"
        case backShiny = "back_shiny"
        case backFemale = "back_female"
        case backShinyFemale = "back_shiny_female"
    }

}
