//
// PokemonList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonList: Codable { 


    public var count: Int?
    public var next: String?
    public var previous: String?
    public var results: [PokemonItem]?

    public init(count: Int?, next: String?, previous: String?, results: [PokemonItem]?) {
        self.count = count
        self.next = next
        self.previous = previous
        self.results = results
    }

}
