//
// PokemonMove.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonMove: Codable { 


    public var move: Move?
    public var versionGroupDetails: [PokemonMoveVersion]?

    public init(move: Move?, versionGroupDetails: [PokemonMoveVersion]?) {
        self.move = move
        self.versionGroupDetails = versionGroupDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case move
        case versionGroupDetails = "version_group_details"
    }

}
