//
// PokemonSpeciesDexEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonSpeciesDexEntry: Codable { 


    public var entryNumber: Int?
    public var pokedex: Pokedex?

    public init(entryNumber: Int?, pokedex: Pokedex?) {
        self.entryNumber = entryNumber
        self.pokedex = pokedex
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case entryNumber = "entry_number"
        case pokedex
    }

}
