//
// PokemonSpeciesVariety.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonSpeciesVariety: Codable { 


    public var isDefault: Bool?
    public var pokemon: Pokemon?

    public init(isDefault: Bool?, pokemon: Pokemon?) {
        self.isDefault = isDefault
        self.pokemon = pokemon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case isDefault = "is_default"
        case pokemon
    }

}
