//
// PokemonHeldItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonHeldItem: Codable { 


    public var item: Item?
    public var versionDetails: [PokemonHeldItemVersion]?

    public init(item: Item?, versionDetails: [PokemonHeldItemVersion]?) {
        self.item = item
        self.versionDetails = versionDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case item
        case versionDetails = "version_details"
    }

}
