//
// PokemonMoveVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonMoveVersion: Codable { 


    public var moveLearnMethod: MoveLearnMethod?
    public var versionGroup: VersionGroup?
    public var levelLearnedAt: Int?

    public init(moveLearnMethod: MoveLearnMethod?, versionGroup: VersionGroup?, levelLearnedAt: Int?) {
        self.moveLearnMethod = moveLearnMethod
        self.versionGroup = versionGroup
        self.levelLearnedAt = levelLearnedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case moveLearnMethod = "move_learn_method"
        case versionGroup = "version_group"
        case levelLearnedAt = "level_learned_at"
    }

}
