//
// PokemonHeldItemVersion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonHeldItemVersion: Codable { 


    public var version: Version?
    public var rarity: Int?

    public init(version: Version?, rarity: Int?) {
        self.version = version
        self.rarity = rarity
    }

}
