//
// PokemonAbility.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RealmSwift

public class PokemonAbility: RealmSwift.Object, Codable {

    @objc dynamic public var ability: Ability?

    public convenience init(ability: Ability?) {
        self.init()
        
        self.ability = ability
    }

}
