//
// PokemonEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonEntry: Codable { 


    public var entryNumber: Int?

    public init(entryNumber: Int?) {
        self.entryNumber = entryNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case entryNumber = "entry_number"
    }

}
