//
// PokemonEncounter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonEncounter: Codable { 


    public var pokemon: Pokemon?
    public var versionDetails: [VersionEncounterDetail]?

    public init(pokemon: Pokemon?, versionDetails: [VersionEncounterDetail]?) {
        self.pokemon = pokemon
        self.versionDetails = versionDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case pokemon
        case versionDetails = "version_details"
    }

}
