//
// PokemonAbility.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonAbility: Codable { 


    public var isHidden: Bool?
    public var slot: Int?
    public var ability: Ability?

    public init(isHidden: Bool?, slot: Int?, ability: Ability?) {
        self.isHidden = isHidden
        self.slot = slot
        self.ability = ability
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case isHidden = "is_hidden"
        case slot
        case ability
    }

}
