//
// PokemonShape.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonShape: Codable { 


    public var id: Int?
    public var name: String?
    public var awesomeNames: [AwesomeName]?
    public var names: [Name]?
    public var pokemonSpecies: [PokemonSpecies]?

    public init(id: Int?, name: String?, awesomeNames: [AwesomeName]?, names: [Name]?, pokemonSpecies: [PokemonSpecies]?) {
        self.id = id
        self.name = name
        self.awesomeNames = awesomeNames
        self.names = names
        self.pokemonSpecies = pokemonSpecies
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case awesomeNames = "awesome_names"
        case names
        case pokemonSpecies = "pokemon_species"
    }

}
