//
// PokemonStat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PokemonStat: Codable { 


    public var stat: Stat?
    public var effort: Int?
    public var baseStat: Int?

    public init(stat: Stat?, effort: Int?, baseStat: Int?) {
        self.stat = stat
        self.effort = effort
        self.baseStat = baseStat
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case stat
        case effort
        case baseStat = "base_stat"
    }

}
