//
// Stat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Stat: Codable { 


    public var id: Int?
    public var name: String?
    public var gameIndex: Int?
    public var isBattleOnly: Bool?
    public var affectingMoves: MoveStatAffectSets?
    public var affectingNatures: NatureStatAffectSets?
    public var characteristics: [Characteristic]?
    public var moveDamageClass: MoveDamageClass?
    public var names: [Name]?

    public init(id: Int?, name: String?, gameIndex: Int?, isBattleOnly: Bool?, affectingMoves: MoveStatAffectSets?, affectingNatures: NatureStatAffectSets?, characteristics: [Characteristic]?, moveDamageClass: MoveDamageClass?, names: [Name]?) {
        self.id = id
        self.name = name
        self.gameIndex = gameIndex
        self.isBattleOnly = isBattleOnly
        self.affectingMoves = affectingMoves
        self.affectingNatures = affectingNatures
        self.characteristics = characteristics
        self.moveDamageClass = moveDamageClass
        self.names = names
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case gameIndex = "game_index"
        case isBattleOnly = "is_battle_only"
        case affectingMoves = "affecting_moves"
        case affectingNatures = "affecting_natures"
        case characteristics
        case moveDamageClass = "move_damage_class"
        case names
    }

}
