//
// SuperContestEffect.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SuperContestEffect: Codable { 


    public var id: Int?
    public var appeal: Int?
    public var flavorTextEntries: [FlavorText]?
    public var moves: [Move]?

    public init(id: Int?, appeal: Int?, flavorTextEntries: [FlavorText]?, moves: [Move]?) {
        self.id = id
        self.appeal = appeal
        self.flavorTextEntries = flavorTextEntries
        self.moves = moves
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case appeal
        case flavorTextEntries = "flavor_text_entries"
        case moves
    }

}
