//
// TypeRelations.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TypeRelations: Codable { 


    public var noDamageTo: [ModelType]?
    public var halfDamageTo: [ModelType]?
    public var doubleDamageTo: [ModelType]?
    public var noDamageFrom: [ModelType]?
    public var halfDamageFrom: [ModelType]?
    public var doubleDamageFrom: [ModelType]?

    public init(noDamageTo: [ModelType]?, halfDamageTo: [ModelType]?, doubleDamageTo: [ModelType]?, noDamageFrom: [ModelType]?, halfDamageFrom: [ModelType]?, doubleDamageFrom: [ModelType]?) {
        self.noDamageTo = noDamageTo
        self.halfDamageTo = halfDamageTo
        self.doubleDamageTo = doubleDamageTo
        self.noDamageFrom = noDamageFrom
        self.halfDamageFrom = halfDamageFrom
        self.doubleDamageFrom = doubleDamageFrom
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case noDamageTo = "no_damage_to"
        case halfDamageTo = "half_damage_to"
        case doubleDamageTo = "double_damage_to"
        case noDamageFrom = "no_damage_from"
        case halfDamageFrom = "half_damage_from"
        case doubleDamageFrom = "double_damage_from"
    }

}
