//
// VersionGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct VersionGroup: Codable { 


    public var id: Int?
    public var name: String?
    public var order: Int?
    public var moveLearnMethods: [MoveLearnMethod]?
    public var pokedexes: [Pokedex]?
    public var regions: [Region]?
    public var versions: [Version]?

    public init(id: Int?, name: String?, order: Int?, moveLearnMethods: [MoveLearnMethod]?, pokedexes: [Pokedex]?, regions: [Region]?, versions: [Version]?) {
        self.id = id
        self.name = name
        self.order = order
        self.moveLearnMethods = moveLearnMethods
        self.pokedexes = pokedexes
        self.regions = regions
        self.versions = versions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case order
        case moveLearnMethods = "move_learn_methods"
        case pokedexes
        case regions
        case versions
    }

}
