//
// VersionGroupFlavorText.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct VersionGroupFlavorText: Codable { 


    public var text: String?
    public var language: Language?
    public var versionGroup: VersionGroup?

    public init(text: String?, language: Language?, versionGroup: VersionGroup?) {
        self.text = text
        self.language = language
        self.versionGroup = versionGroup
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case text
        case language
        case versionGroup = "version_group"
    }

}
