//
// VersionEncounterDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct VersionEncounterDetail: Codable { 


    public var version: Version?
    public var maxChance: Int?
    public var encounterDetails: [Encounter]?

    public init(version: Version?, maxChance: Int?, encounterDetails: [Encounter]?) {
        self.version = version
        self.maxChance = maxChance
        self.encounterDetails = encounterDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case version
        case maxChance = "max_chance"
        case encounterDetails = "encounter_details"
    }

}
