//
// VersionGameIndex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RealmSwift

public class VersionGameIndex: RealmSwift.Object, Codable {
    
    public var gameIndex: RealmOptional<Int> = .init(nil)
    @objc dynamic public var version: Version?
    
    public var infoText: String {
        (self.gameIndex.value?.description ?? "") + " ver: " + (self.version?.name ?? "")
    }
    
    public required convenience init(from decoder: Decoder) throws {
        self.init()
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.gameIndex = .init(try? container.decode(Int.self, forKey: .gameIndex))
        self.version = try? container.decode(Version.self, forKey: .version)
    }
    
    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case gameIndex = "game_index"
        case version
    }
}
