//
// VersionGameIndex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct VersionGameIndex: Codable { 


    public var gameIndex: Int?
    public var version: Version?

    public init(gameIndex: Int?, version: Version?) {
        self.gameIndex = gameIndex
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case gameIndex = "game_index"
        case version
    }

}
