//
// Weakness.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Weakness: Codable { 


    public var type: String?
    public var value: String?

    public init(type: String?, value: String?) {
        self.type = type
        self.value = value
    }

}
