//
// Weakness.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import RealmSwift

public class Weakness: RealmSwift.Object, Codable {


    @objc dynamic public var type: String?
    @objc dynamic public var value: String?

    public convenience init(type: String?, value: String?) {
        self.init()
        
        self.type = type
        self.value = value
    }

}
