//
// PokemonAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class PokemonAPI {
    /**
     Returns a list of pokemons
     
     - parameter limit: (query) Count of items (optional)
     - parameter offset: (query) Offset for next page (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getPokemonList(limit: Int? = nil, offset: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: PokemonList?,_ error: Error?) -> Void)) {
        getPokemonListWithRequestBuilder(limit: limit, offset: offset).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Returns a list of pokemons
     - GET /pokemon
     - parameter limit: (query) Count of items (optional)
     - parameter offset: (query) Offset for next page (optional)
     - returns: RequestBuilder<PokemonList> 
     */
    open class func getPokemonListWithRequestBuilder(limit: Int? = nil, offset: Int? = nil) -> RequestBuilder<PokemonList> {
        let path = "/pokemon"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": limit?.encodeToJSON(), 
            "offset": offset?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<PokemonList>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
